{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "infrabin.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}  
  labels:
{{ include "infrabin.labels" . | indent 4 }}
{{- end -}}
