- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v1.2.3
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-merge-conflict
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: sort-simple-yaml
