apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: infrabin
  labels:
    app: infrabin
    version: 0.9.1
  name: infrabin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: infrabin
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: infrabin
    spec:
      containers:
        - name: infrabin
          image: maruina/infrabin:0.9.2
          ports:
            - name: http 
              containerPort: 8080
          lifecycle:
            preStop:
              exec:
                # > 3 consecutive failures on the readiness probe
                command: ["sleep","8"]
          livenessProbe:
            httpGet:
              path: /healthcheck/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthcheck/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          env:
          - name: USE_ENVOY_PREFLIGHT
            value: "false"
