---
apiVersion: v1
kind: Namespace
metadata:
  name: infrabin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: infrabin
  labels:
    run: infrabin
  name: infrabin
spec:
  replicas: 3
  selector:
    matchLabels:
      run: infrabin
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
      labels:
        run: infrabin
    spec:
      containers:
        - name: infrabin
          image: maruina/infrabin:0.9.1
          ports:
            - containerPort: 8080
          lifecycle:
            preStop:
              exec:
                # > 3 consecutive failures on the readiness probe
                command: ["sleep","8"]
          livenessProbe:
            httpGet:
              path: /healthcheck/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthcheck/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: infrabin
  labels:
    run: infrabin
  name: infrabin
spec:
  ports:
    - name: port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: infrabin
