---
apiVersion: v1
kind: Service
metadata:
  namespace: infrabin
  labels:
    run: infrabin
  name: infrabin
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: infrabin
