---
apiVersion: v1
kind: Service
metadata:
  namespace: infrabin
  labels:
    app: infrabin
  name: infrabin
spec:
  ports:
    - name: http-service
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: infrabin
